### ISSUE TITLE
Scrap 다중 클릭 제한

### ISSUE THREAD

**Issue by bjc1102** [GDSC-Daejin/gdsc-dju-websites#102]
# **어떤 기능을 추가/요청하나요?**

[//]: # ( A clear and concise description of what the problem is. Ex. I'm always frustrated when I can't find a way to do X. )

## 작업 상세 내용

- [ ] scrap 클릭 요청 제한 및 성능 최적화

**Comment by HyeokE** [comment]
@all-contributors please add @bjc1102 for develop

**Comment by HyeokE** [comment]
https://github.com/all-contributors please add @bjc1102 for code

**Comment by HyeokE** [comment]
@all-contributors please add @bjc1102 for code
